name: Label issue on close

on:
  issues:
    types: [closed]

jobs:
  label-on-close:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Required to add labels to issues

    steps:
      - name: Add 'done' label to closed issue
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              labels: ['documentation']  // <-- Change to your preferred label
            });
