name: Move issue to "In review" in Projects v2

on:
  push:
    branches:
      - main

jobs:
  update-project-status:
    runs-on: ubuntu-latest

    steps:
      - name: Update Project field to "In review" for referenced issues
        env:
          GH_TOKEN: ${{ secrets.GH_PROJECTS_TOKEN }}
        uses: actions/github-script@v7
        with:
          script: |
            const issuePattern = /(?:#|gh-)(\d+)/gi;
            const projectId = "PVT_kwHODArNsc4A4n6f"; // your project
            const fieldId = "PVTSSF_lAHODArNsc4A4n6fzgtj29U"; // Status field
            const inReviewOptionId = "df73e18b"; // "In review" option
            const commits = context.payload.commits;
            const issueNumbers = new Set();

            for (const commit of commits) {
              let match;
              while ((match = issuePattern.exec(commit.message)) !== null) {
                issueNumbers.add(Number(match[1]));
              }
            }

            if (issueNumbers.size === 0) {
              console.log("No referenced issues found.");
              return;
            }

            const graphqlWithAuth = github.graphql.defaults({
              headers: {
                authorization: `Bearer ${process.env.GH_TOKEN}`,
              },
            });

            for (const issueNumber of issueNumbers) {
              console.log(`Processing issue #${issueNumber}`);

              // Step 1: Get the issue's node ID
              const issueData = await graphqlWithAuth(`
                query($owner: String!, $repo: String!, $issue: Int!) {
                  repository(owner: $owner, name: $repo) {
                    issue(number: $issue) {
                      id
                    }
                  }
                }
              `, {
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue: issueNumber
              });

              const issueId = issueData.repository.issue.id;
              console.log(`Issue node ID: ${issueId}`);

              // Step 2: Get the project item ID for this issue
              const itemData = await graphqlWithAuth(`
                query($projectId: ID!, $contentId: ID!) {
                  projectV2ItemByContent(projectId: $projectId, contentId: $contentId) {
                    id
                  }
                }
              `, {
                projectId,
                contentId: issueId
              });

              const itemId = itemData.projectV2ItemByContent?.id;

              if (!itemId) {
                console.log(`❌ Issue #${issueNumber} is not in the project. Skipping.`);
                continue;
              }

              console.log(`✅ Found project item ID: ${itemId}`);

              // Step 3: Update the field to "In review"
              await graphqlWithAuth(`
                mutation {
                  updateProjectV2ItemFieldValue(
                    input: {
                      projectId: "${projectId}",
                      itemId: "${itemId}",
                      fieldId: "${fieldId}",
                      value: {
                        singleSelectOptionId: "${inReviewOptionId}"
                      }
                    }
                  ) {
                    projectV2Item {
                      id
                    }
                  }
                }
              `);

              console.log(`🎯 Updated issue #${issueNumber} to "In review"`);
            }
